<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    第一点，前面已经说过，await命令后面的Promise对象，运行结果可能是rejected，所以最好把await命令放在try...catch代码块中。

    <script>
        async function myFunction() {
            try {
                await somethingThatReturnsAPromise();
            } catch (err) {
                console.log(err);
            }
        }

        // 另一种写法

        async function myFunction() {
            await somethingThatReturnsAPromise()
                .catch(function (err) {
                    console.log(err);
                });
        }
    </script>

    第二点，多个await命令后面的异步操作，如果不存在继发关系，最好让它们同时触发。
    let foo = await getFoo();
    let bar = await getBar();
    <script>
        // 写法一
        let [foo, bar] = await Promise.all([getFoo(), getBar()]);

        // 写法二
        let fooPromise = getFoo();
        let barPromise = getBar();
        let foo = await fooPromise;
        let bar = await barPromise;
    </script>

    第三点，await命令只能用在async函数之中，如果用在普通函数，就会报错。
</body>

</html>